In [ ]:
train_txt = """i like to get a hamburger
i like to eat a pizza
i want to eat food from malaysia
i would like to eat some chinese food
i would like to go to a japanese restaurant
"""

In [ ]:
sentences = [sent.split() for sent in train_txt.splitlines()]

In [ ]:
import nltk
from collections import defaultdict, Counter

Ns = (1,2,3)
bos = '<s>' #begining
eos = '</s>' #end

ngram_cnt = defaultdict(Counter)

for sent in sentences:
  for N  in Ns:
    ngram_list = nltk.ngrams(sent, N, pad_left=True, left_pad_symbol=bos)
    for ngram in ngram_list:
      history = ngram[:-1]
      word = ngram[-1]
      ngram_cnt[history][word] += 1

In [ ]:
from pprint import pprint
pprint(ngram_cnt)

defaultdict(<class 'collections.Counter'>,
            {(): Counter({'to': 6,
                          'i': 5,
                          'like': 4,
                          'a': 3,
                          'eat': 3,
                          'food': 2,
                          'would': 2,
                          'get': 1,
                          'hamburger': 1,
                          'pizza': 1,
                          'want': 1,
                          'from': 1,
                          'malaysia': 1,
                          'some': 1,
                          'chinese': 1,
                          'go': 1,
                          'japanese': 1,
                          'restaurant': 1}),
             ('<s>',): Counter({'i': 5}),
             ('<s>', '<s>'): Counter({'i': 5}),
             ('<s>', 'i'): Counter({'like': 2, 'would': 2, 'want': 1}),
             ('a',): Counter({'hamburger': 1, 'pizza': 1, 'japanese': 1}),
             ('a', 'japanese'): Counter(

In [ ]:
test_txt = 'i wnat to eat a hamburger'
test = test_txt.split()
k = len(test)

In [ ]:
import numpy as np
test_ngram_probs_dict = dict()
for N in Ns:
  ngrams = nltk.ngrams(test, N, pad_left=True, left_pad_symbol=bos)
  probs = []
  for ngram in ngrams:
    history = ngram[:-1]
    word = ngram[-1]
    cnt = ngram_cnt[history]
    probs.append(cnt[word]/sum(cnt.values()))
  test_ngram_probs_dict[N] = probs

ZeroDivisionError: ignored

In [ ]:
test_ngram_probs_dict

{1: [0.1388888888888889,
  0.0,
  0.16666666666666666,
  0.08333333333333333,
  0.08333333333333333,
  0.027777777777777776]}

In [ ]:
import numpy as np

In [ ]:
v = np.array([1,3,1])
print(v.shape)

(3,)


In [ ]:
m1 = np.array([[1, 3, 1], [1, 0, 0]])
print(m1)
print(m1.shape)

[[1 3 1]
 [1 0 0]]
(2, 3)


In [ ]:
m2 = np.array([[0,0,5], [7,5,0]])
print(m1+m2)

[[1 3 6]
 [8 5 0]]


In [ ]:
print(2*m1)

[[2 6 2]
 [2 0 0]]


In [ ]:
m1_t = np.transpose(m1)
print(m1_t.shape)

(3, 2)


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#항등행렬
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#행렬의 곱셈
np.dot(m1, m2) #모양이 맞지 않는 경우 value 에러 발생

In [ ]:
np.dot(m1_t, m2)

array([[ 7,  5,  5],
       [ 0,  0, 15],
       [ 0,  0,  5]])

In [ ]:
np.dot(m1, np.transpose(m2))

array([[ 5, 22],
       [ 0,  7]])

In [ ]:
#열항렬 : 덧셈에 대한 항등원
#항등행렬: 곱셈에 대한 항등원
np.dot(m1, np.identity(3)) == m1

array([[ True,  True,  True],
       [ True,  True,  True]])